### ISSUE TITLE
No fonts were found

### ISSUE THREAD

**Issue by OrenShalmy** [Nucs/FontRegister#1]
FontRegister.exe is in C:\Windows\System32\
I copied a new font to c:\newfont
Running `FontRegister C:\newfont` outputs:

> Accepted arguments:
> No fonts were found.

Any suggestions?

**Comment by Nucs** [comment]
The issue:
When you give a path to FontRegister.exe with fonts in it to install,
it copies them to the exe's location for temporary storage,
in your case "C:\Windows\System32\temp" and removes them when it finishes install.

Temporary fix:
Move it to a writable folder, e.g. %USERPROFILE%.
And if you want it available in any cmd, add that folder to PATH.

In future release (1.01b):
The exe will check writability first, and will have plenty fallbacks.. just in case.

Thanks for reporting,
ובהצלחה אם מה שלא יהיה שאתה כותב שם :)

**Comment by Nucs** [comment]
Thanks for reporting,
The issue has been resolved and the cache folder has been changed to %temp% instead of "exe"'s location which in your case was sys32 folder.
Only if %TEMP% is unavailble, only then it will attempt to write to sys32 windir.

תודה ובהצלחה עם מה שאתה כותב שם :)
